---
name: test
on:
  pull_request:
  push:
    branches:
    - gh-readonly-queue/**
    - master
jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python:
        - "3.10"
        - "3.9"
        - "3.8"
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python }}
        cache: pip
        cache-dependency-path: setup.py
    - run: pip install tox==3.26.0
    - run: tox
